services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paddlex_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
